version: "3.9"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
  app:
    container_name: app
    build: ./docker/php
    ports:
      - 5173:5173
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./src:/var/www/html
  mysql:
    container_name: mysql
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.conf:/etc/mysql/my.conf
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWPRD: password
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_ROOT_PASSWORD=rootpassword
volumes:
  mysql-volume:
